package io.shamanic.android.db.src_gen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import io.shamanic.android.db.src_gen.user;
import io.shamanic.android.db.src_gen.userlocation;
import io.shamanic.android.db.src_gen.hull;

import io.shamanic.android.db.src_gen.userDao;
import io.shamanic.android.db.src_gen.userlocationDao;
import io.shamanic.android.db.src_gen.hullDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig userlocationDaoConfig;
    private final DaoConfig hullDaoConfig;

    private final userDao userDao;
    private final userlocationDao userlocationDao;
    private final hullDao hullDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(userDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userlocationDaoConfig = daoConfigMap.get(userlocationDao.class).clone();
        userlocationDaoConfig.initIdentityScope(type);

        hullDaoConfig = daoConfigMap.get(hullDao.class).clone();
        hullDaoConfig.initIdentityScope(type);

        userDao = new userDao(userDaoConfig, this);
        userlocationDao = new userlocationDao(userlocationDaoConfig, this);
        hullDao = new hullDao(hullDaoConfig, this);

        registerDao(user.class, userDao);
        registerDao(userlocation.class, userlocationDao);
        registerDao(hull.class, hullDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        userlocationDaoConfig.getIdentityScope().clear();
        hullDaoConfig.getIdentityScope().clear();
    }

    public userDao getUserDao() {
        return userDao;
    }

    public userlocationDao getUserlocationDao() {
        return userlocationDao;
    }

    public hullDao getHullDao() {
        return hullDao;
    }

}
