package io.shamanic.android.db.src_gen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import io.shamanic.android.db.src_gen.location;

import io.shamanic.android.db.src_gen.locationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;

    private final locationDao locationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(locationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        locationDao = new locationDao(locationDaoConfig, this);

        registerDao(location.class, locationDao);
    }
    
    public void clear() {
        locationDaoConfig.getIdentityScope().clear();
    }

    public locationDao getLocationDao() {
        return locationDao;
    }

}
