package io.shamanic.android.db.src_gen;

import java.util.List;
import io.shamanic.android.db.src_gen.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HULL.
 */
public class hull {

    private Long id;
    /** Not-null value. */
    private String hullJson;
    private String hullCentroidJson;
    private java.util.Date timestamp;
    private Long userId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient hullDao myDao;

    private user user;
    private Long user__resolvedKey;

    private List<userlocation> userlocationList;

    public hull() {
    }

    public hull(Long id) {
        this.id = id;
    }

    public hull(Long id, String hullJson, String hullCentroidJson, java.util.Date timestamp, Long userId) {
        this.id = id;
        this.hullJson = hullJson;
        this.hullCentroidJson = hullCentroidJson;
        this.timestamp = timestamp;
        this.userId = userId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getHullDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getHullJson() {
        return hullJson;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHullJson(String hullJson) {
        this.hullJson = hullJson;
    }

    public String getHullCentroidJson() {
        return hullCentroidJson;
    }

    public void setHullCentroidJson(String hullCentroidJson) {
        this.hullCentroidJson = hullCentroidJson;
    }

    public java.util.Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /** To-one relationship, resolved on first access. */
    public user getUser() {
        Long __key = this.userId;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            userDao targetDao = daoSession.getUserDao();
            user userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(user user) {
        synchronized (this) {
            this.user = user;
            userId = user == null ? null : user.getId();
            user__resolvedKey = userId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<userlocation> getUserlocationList() {
        if (userlocationList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            userlocationDao targetDao = daoSession.getUserlocationDao();
            List<userlocation> userlocationListNew = targetDao._queryHull_UserlocationList(id);
            synchronized (this) {
                if(userlocationList == null) {
                    userlocationList = userlocationListNew;
                }
            }
        }
        return userlocationList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetUserlocationList() {
        userlocationList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
